/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import clases.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import mysql.Conexion;

/**
 *
 * @author DAW
 */
public class InicioSesion extends javax.swing.JFrame {

    private static final Conexion conexion = Conexion.getInstance();

    /**
     * Creates new form app
     */
    public InicioSesion() {
        initComponents();
        this.setTitle("Iniciar sesión");
        this.setSize(750, 500);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        user_pass_incorrecto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_usuario = new javax.swing.JTextField();
        jb_entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_pass_incorrecto = new javax.swing.JLabel();
        jtf_password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(200, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jtf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 150, -1));

        jb_entrar.setText("Entrar");
        jb_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, -1));

        jLabel1.setLabelFor(jtf_password);
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel2.setLabelFor(jtf_usuario);
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        user_pass_incorrecto.setForeground(new java.awt.Color(255, 0, 51));
        user_pass_incorrecto.setText("El usuario o contraseña son incorrectos");
        getContentPane().add(user_pass_incorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jtf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(jtf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, -1));

        jPanel1.setBackground(new java.awt.Color(85, 26, 2));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 450, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void entrar() throws SQLException {
        String usuario, password;
        usuario = jtf_usuario.getText();
        password = jtf_password.getText();
        Empleado user = conexion.iniciarSesion(usuario, password);
        if (user != null) {
            jtf_password.setBackground(Color.WHITE);
            user_pass_incorrecto.setVisible(false);
            JFrame main = new Aplicacion(user);
            this.dispose();
            main.setVisible(true);
        } else {
            jtf_password.setBackground(Color.RED);
            user_pass_incorrecto.setVisible(true);
        }
        

    }

    private void jb_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarActionPerformed
        try {
            // TODO add your handling code here:
            entrar();
        } catch (SQLException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_entrarActionPerformed


    private void jtf_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_usuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            try {
                System.out.println(jtf_usuario.getText());
                entrar();
            } catch (SQLException ex) {
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtf_usuarioKeyPressed

    private void jtf_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_passwordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            try {
                entrar();
            } catch (SQLException ex) {
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtf_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JPasswordField jtf_password;
    private javax.swing.JTextField jtf_usuario;
    private javax.swing.JLabel user_pass_incorrecto;
    // End of variables declaration//GEN-END:variables
}
