/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.*;
import conexion.Conexion;

/**
 *
 * @author DAW
 */
public class Inicio_sesion extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public Inicio_sesion() {
        initComponents();
        this.setSize(300, 300);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        user_pass_incorrecto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_usuario = new javax.swing.JTextField();
        jb_entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_pass_incorrecto = new javax.swing.JLabel();
        jtf_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(200, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usuarioActionPerformed(evt);
            }
        });
        jtf_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jtf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        jb_entrar.setText("Entrar");
        jb_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, -1));

        jLabel1.setLabelFor(jtf_password);
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel2.setLabelFor(jtf_usuario);
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        user_pass_incorrecto.setForeground(new java.awt.Color(255, 0, 51));
        user_pass_incorrecto.setText("El usuario o contraseña son incorrectos");
        getContentPane().add(user_pass_incorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jtf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(jtf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usuarioActionPerformed

    public void entrar() {
        String usuario;
        String password;
        usuario = jtf_usuario.getText();
        password = jtf_password.getText();
        System.out.println(password);
        Conexion conexion = Conexion.getInstance();
        if (conexion.InciarSesion(this.jtf_password, this.user_pass_incorrecto, usuario, password)) {
            if (conexion.ComprobarRoleUsuario(usuario)) {
                JFrame main = new MainApp(usuario, true);
                this.dispose();
                main.show();
            } else {
                JFrame main = new MainApp(usuario, false);
                this.dispose();
                main.show();
            }

        }
    }

    private void jb_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarActionPerformed
        // TODO add your handling code here:
        entrar();
    }//GEN-LAST:event_jb_entrarActionPerformed


    private void jtf_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_usuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            System.out.println(jtf_usuario.getText());
            entrar();
        }
    }//GEN-LAST:event_jtf_usuarioKeyPressed

    private void jtf_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_passwordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            entrar();
        }
    }//GEN-LAST:event_jtf_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JPasswordField jtf_password;
    private javax.swing.JTextField jtf_usuario;
    private javax.swing.JLabel user_pass_incorrecto;
    // End of variables declaration//GEN-END:variables
}
